dist: ubuntu
language: java
jdk:
- openjdk8
script:
- "./mvnw clean test -P test"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: heroku
  api_key:
    secure: code
  app:
    master: adm-c-test
  on:
    repo: viniciusecortez/alugo-camada-Adm
