dist: ubuntu
language: java
jdk:
- openjdk8
script:
- "./mvnw clean test -P test"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: heroku
  api_key:
    secure: jtL0MDMjwOPLe9wWREk9mXR6CU5FTEe6zA1VDLMZgy/PTXfLjTtmnFG+ESWokdRDNPPWaNo95MheRF0LOak/D6PWUihEMKk7CuHxtIHD4IgPhs8UBpCw1B5gpyTRd6rRw9m9Qwdu31S+WLQpuT3w9NAoVxB9icKoG79VasAHGCCIxbasLKH7e2lmWS80X1Jb8z68WYHryZzNuyoZ76thDB0uiS+jLy9B+p63Dw+RPsNhMp/28cHKFNmcRGOlbONuOK2oAgFxlWtLuNwamW2aT9523gQKAakbGeFHJ3e6Y8aoeIVxee6ymkAB8L9mYzPBEYrGnjFSfKjh+OFZyVBnRV5ZECN8nOuFJLRwHnsRVomT4ItJCEr8QQD/n36vteJjSKWN3rTa6+L1WDr2L1sc6WFshtC1+e7fVWQM1a90qZRcnJOFZcpU1/+19wlzHncYMs6FUqXhHfExU71BTmH95mLQLzLL5JRuJhjLV7em5UCL5aXF7qC+MqHeLZ+VlrjCaxEu6GR1cMGBS6zFQZfIg7fsiMJDiEgfiBCNzwe3c1u8yYtwpXLzellH1hzzmt26XlQo6a18TkCBuLXHw93c0W6JxoDTJ6YhEn4d9lNt4l9Q9DMo5DKBreDCNdXiEhPVybD35qhm2z7Aa5R7cmbrsVmeE4KVl//NDpnE/G/1/rI=
  app:
    master: camada-adm
  on:
    repo: onlycoders-ifsp/alugo-camada-Adm
